"use client";
import { useState } from "react";
import {
  Copy, RotateCcw, CheckCheck, FileDown, Layers, FileText,
} from "lucide-react";
import { STEPS } from "@/lib/constants";

export default function ExportActions({ stepData, siteUrl, onReset }) {
  const [copied, setCopied] = useState(false);
  const [pdfLoading, setPdfLoading] = useState(false);

  // ── Build clean text for all steps ──────────────────────────────
  function buildFullText() {
    const missing = STEPS.filter((s) => !stepData[s.id]?.text);
    const text = STEPS.map((s) => {
      const d = stepData[s.id];
      if (!d?.text) return `\n\n═══ STEP ${s.id}: ${s.label.toUpperCase()} ═══\n\n[NOT COMPLETED]\n`;
      return `\n\n═══ STEP ${s.id}: ${s.label.toUpperCase()} ═══\n\n${d.text}`;
    }).join("\n");

    if (missing.length > 0) {
      const ids = missing.map((s) => s.id).join(", ");
      if (!confirm(`Steps ${ids} are incomplete.\n\nProceed with export anyway?`)) return null;
    }
    return text;
  }

  // ── Copy all ─────────────────────────────────────────────────────
  async function handleCopy() {
    const fullText = buildFullText();
    if (!fullText) return;
    try {
      await navigator.clipboard.writeText(fullText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      alert("Could not copy to clipboard.");
    }
  }

  // ── PDF Export (jsPDF) ────────────────────────────────────────────
  async function handlePDF() {
    setPdfLoading(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });

      const pageW  = doc.internal.pageSize.getWidth();
      const pageH  = doc.internal.pageSize.getHeight();
      const margin = 18;
      const maxW   = pageW - margin * 2;
      let y = 0;

      // ── Colour palette ──────────────────────────────────────────
      const RED      = [225, 29, 72];
      const DARK     = [15, 23, 42];
      const MUTED    = [100, 116, 139];
      const WHITE    = [255, 255, 255];
      const LIGHT_BG = [248, 250, 252];
      const BORDER   = [226, 232, 240];

      function addPage() {
        doc.addPage();
        // Subtle top border on new pages
        doc.setDrawColor(...RED);
        doc.setLineWidth(0.5);
        doc.line(0, 0, pageW, 0);
        y = margin;
      }

      function checkPageBreak(needed = 10) {
        if (y + needed > pageH - margin) addPage();
      }

      // ── Cover page ──────────────────────────────────────────────
      // Background
      doc.setFillColor(...WHITE);
      doc.rect(0, 0, pageW, pageH, "F");

      // Red accent strip
      doc.setFillColor(...RED);
      doc.rect(0, 0, pageW, 42, "F");

      // Title
      doc.setFont("helvetica", "bold");
      doc.setFontSize(26);
      doc.setTextColor(...WHITE);
      doc.text("SEO Analysis Report", margin, 22);

      // Subtitle
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(255, 200, 210);
      const cleanUrl = siteUrl.replace(/^https?:\/\//, "");
      doc.text(cleanUrl, margin, 32);

      // Meta info
      doc.setFillColor(...LIGHT_BG);
      doc.roundedRect(margin, 52, maxW, 28, 3, 3, "F");
      doc.setDrawColor(...BORDER);
      doc.setLineWidth(0.3);
      doc.roundedRect(margin, 52, maxW, 28, 3, 3, "S");

      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(...MUTED);
      doc.text("Generated by SEO Agent", margin + 6, 62);
      doc.text(`Date: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, margin + 6, 70);

      // Steps summary on cover
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(...DARK);
      doc.text("Contents", margin, 96);

      doc.setLineWidth(0.3);
      doc.setDrawColor(...RED);
      doc.line(margin, 99, margin + 30, 99);

      STEPS.forEach((s, i) => {
        const d = stepData[s.id];
        const isDone = d?.status === "done";
        const yCover = 106 + i * 9;

        doc.setFillColor(isDone ? 16 : 200, isDone ? 185 : 200, isDone ? 129 : 200);
        doc.circle(margin + 2.5, yCover - 1.5, 2, "F");
        doc.setFont("helvetica", isDone ? "normal" : "italic");
        doc.setFontSize(10);
        doc.setTextColor(...(isDone ? DARK : MUTED));
        doc.text(`Step ${s.id}: ${s.label}${isDone ? "" : " (incomplete)"}`, margin + 7, yCover);
      });

      // ── Content pages ────────────────────────────────────────────
      addPage();

      STEPS.forEach((step) => {
        const d = stepData[step.id];

        checkPageBreak(24);

        // Step header banner
        doc.setFillColor(...RED);
        doc.roundedRect(margin, y, maxW, 14, 2, 2, "F");

        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.setTextColor(...WHITE);
        doc.text(`STEP ${step.id}  ·  ${step.label.toUpperCase()}`, margin + 5, y + 9);
        y += 18;

        if (!d?.text) {
          doc.setFont("helvetica", "italic");
          doc.setFontSize(9);
          doc.setTextColor(...MUTED);
          doc.text("This step was not completed.", margin, y);
          y += 12;
          return;
        }

        // Quality score chip (Step 6)
        if (d.quality) {
          const qScore = d.quality.qualityScore;
          const qColor = qScore >= 80 ? [16, 185, 129] : qScore >= 60 ? [245, 158, 11] : [239, 68, 68];
          doc.setFillColor(...qColor);
          doc.roundedRect(margin, y, 36, 7, 1.5, 1.5, "F");
          doc.setFont("helvetica", "bold");
          doc.setFontSize(7);
          doc.setTextColor(...WHITE);
          doc.text(`✦ ${qScore}% Quality`, margin + 2, y + 5);
          y += 11;
        }

        // Body text — parse markdown headings lightly
        const rawText = d.text;
        const lines = rawText.split("\n");

        for (const line of lines) {
          checkPageBreak(8);

          const trimmed = line.trim();
          if (!trimmed) { y += 3; continue; }

          if (trimmed.startsWith("## ")) {
            y += 3;
            checkPageBreak(12);
            doc.setFont("helvetica", "bold");
            doc.setFontSize(12);
            doc.setTextColor(...RED);
            const heading = trimmed.replace(/^## /, "");
            doc.text(heading, margin, y);
            // Underline
            const w = doc.getTextWidth(heading);
            doc.setDrawColor(...RED);
            doc.setLineWidth(0.4);
            doc.line(margin, y + 1, margin + w, y + 1);
            y += 8;

          } else if (trimmed.startsWith("### ")) {
            y += 2;
            checkPageBreak(10);
            doc.setFont("helvetica", "bold");
            doc.setFontSize(10);
            doc.setTextColor(...DARK);
            doc.text(trimmed.replace(/^### /, ""), margin, y);
            y += 7;

          } else if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
            doc.setFillColor(...RED);
            doc.circle(margin + 1.5, y - 1.5, 1, "F");
            doc.setFont("helvetica", "normal");
            doc.setFontSize(9);
            doc.setTextColor(...DARK);
            const bulletText = trimmed.replace(/^[-*]\s+/, "").replace(/\*\*/g, "");
            const wrapped = doc.splitTextToSize(bulletText, maxW - 6);
            wrapped.forEach((wl, wi) => {
              checkPageBreak(6);
              doc.text(wl, margin + 5, y);
              y += 5;
            });

          } else if (/^\d+\./.test(trimmed)) {
            doc.setFont("helvetica", "bold");
            doc.setFontSize(9);
            doc.setTextColor(...RED);
            const numMatch = trimmed.match(/^(\d+\.)\s+(.*)/);
            if (numMatch) {
              doc.text(numMatch[1], margin, y);
              doc.setFont("helvetica", "normal");
              doc.setTextColor(...DARK);
              const numbered = numMatch[2].replace(/\*\*/g, "");
              const wrapped = doc.splitTextToSize(numbered, maxW - 8);
              wrapped.forEach((wl, wi) => {
                checkPageBreak(6);
                doc.text(wl, margin + 6, y);
                y += 5;
              });
            }

          } else if (trimmed.startsWith("|")) {
            // Simple table row — just output as plain text
            doc.setFont("courier", "normal");
            doc.setFontSize(8);
            doc.setTextColor(...MUTED);
            const tableRow = trimmed.replace(/\|/g, " ").trim().replace(/\*\*/g, "");
            const wrapped = doc.splitTextToSize(tableRow, maxW);
            wrapped.forEach((wl) => {
              checkPageBreak(5);
              doc.text(wl, margin, y);
              y += 4.5;
            });

          } else {
            doc.setFont("helvetica", "normal");
            doc.setFontSize(9);
            doc.setTextColor(...DARK);
            const plain = trimmed.replace(/\*\*/g, "");
            const wrapped = doc.splitTextToSize(plain, maxW);
            wrapped.forEach((wl) => {
              checkPageBreak(6);
              doc.text(wl, margin, y);
              y += 5;
            });
          }
        }

        y += 10; // Space after each step
      });

      // ── Footer on every page ─────────────────────────────────────
      const totalPages = doc.internal.getNumberOfPages();
      for (let p = 1; p <= totalPages; p++) {
        doc.setPage(p);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7);
        doc.setTextColor(...MUTED);
        doc.text(`SEO Agent  ·  ${cleanUrl}`, margin, pageH - 6);
        doc.text(`Page ${p} of ${totalPages}`, pageW - margin, pageH - 6, { align: "right" });
        doc.setDrawColor(...BORDER);
        doc.setLineWidth(0.2);
        doc.line(margin, pageH - 9, pageW - margin, pageH - 9);
      }

      // ── Save ─────────────────────────────────────────────────────
      const slug = siteUrl.replace(/^https?:\/\//, "").replace(/[^a-z0-9]/gi, "-").toLowerCase();
      doc.save(`seo-report-${slug}.pdf`);
    } catch (err) {
      console.error("PDF generation failed:", err);
      alert("PDF export failed. Please try again.");
    } finally {
      setPdfLoading(false);
    }
  }

  // ── Copy all as markdown (keep this as fallback) ─────────────────
  return (
    <div className="export-panel">
      <div className="export-panel-header">
        <Layers size={14} strokeWidth={2} style={{ color: "var(--text-muted)" }} />
        <span className="export-panel-title">Export Report</span>
      </div>
      <div className="export-row">
        {/* PDF — primary CTA */}
        <button
          className="export-btn primary-export"
          onClick={handlePDF}
          disabled={pdfLoading}
        >
          {pdfLoading ? (
            <>
              <span className="spin" style={{ display: "inline-block", width: 14, height: 14, border: "2px solid rgba(255,255,255,0.3)", borderTopColor: "#fff", borderRadius: "50%" }} />
              Generating PDF…
            </>
          ) : (
            <>
              <FileText size={14} strokeWidth={2} />
              Export as PDF
            </>
          )}
        </button>

        {/* Copy as text */}
        <button className="export-btn" onClick={handleCopy}>
          {copied ? <CheckCheck size={14} strokeWidth={2.5} /> : <Copy size={14} strokeWidth={2} />}
          {copied ? "Copied!" : "Copy All Text"}
        </button>

        {/* New analysis */}
        <button className="export-btn reset-btn" onClick={onReset}>
          <RotateCcw size={14} strokeWidth={2} />
          New Analysis
        </button>
      </div>
    </div>
  );
}
